version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: foodhub_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456@
      POSTGRES_DB: FoodHubDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - foodhub-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodhub_backend
    restart: always
    depends_on:
      - db
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=FoodHubDb;Username=postgres;Password=123456@
      - Jwt__SecretKey=FoodHub-SuperSecretKey-2024-MinLength-32Characters-Required-For-Security
      - Jwt__Issuer=FoodHub_Server
      - Jwt__Audience=FoodHub_Client
      - ConnectionStrings__Redis=redis:6379
      - Redis__ConnectionString=redis:6379
      - Redis__InstanceName=FoodHubCache
      - EMAIL_SMTP_HOST=smtp.gmail.com
      - EMAIL_SMTP_PORT=587
      - EMAIL_SENDER_EMAIL=foodhubojt.noreply@gmail.com
      - EMAIL_SENDER_NAME=FoodHub
      - EMAIL_APP_PASSWORD=zdmtalaxyyyaodib
      - JWT_ACCESS_TOKEN_EXPIRES_IN_MINUTE=60
      - JWT_REFRESH_TOKEN_EXPIRES_IN_DAYS=7
    ports:
      - "5000:5000"
    networks:
      - foodhub-network

  redis:
    image: redis:alpine
    container_name: foodhub_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - foodhub-network
    command: redis-server --appendonly yes

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foodhub_frontend
    depends_on:
      - backend
    environment:
      # URL Backend cho Next.js rewrite/proxy
      - API_URL=http://backend:5000
      # URL Backend khi gọi trực tiếp từ Browser
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    ports:
      - "3000:3000"
    networks:
      - foodhub-network

volumes:
  postgres_data:
  redis_data:
networks:
  foodhub-network:
    driver: bridge
